<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\img\icon.ico</ApplicationIcon>
    <AssemblyName>PersonalWikiClient</AssemblyName>
    <RootNamespace>PersonalWikiClient</RootNamespace>
    <PublishDocumentationFiles>false</PublishDocumentationFiles>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="4.152.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="4.152.1" />
  </ItemGroup>
  <ItemGroup>
    <None Include="$(NuGetPackageRoot)skiasharp\4.152.1\LICENSE.txt" Link="SkiaSharp-LICENSE.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="$(NuGetPackageRoot)skiasharp.nativeassets.win32\4.152.1\THIRD-PARTY-NOTICES.txt" Link="SkiaSharp-THIRD-PARTY-NOTICES.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
  <Target Name="ExcludeSkiaSharpNativeDebugSymbols" AfterTargets="ComputeFilesToPublish">
    <ItemGroup>
      <ResolvedFileToPublish Remove="@(ResolvedFileToPublish)" Condition="'%(ResolvedFileToPublish.Filename)%(ResolvedFileToPublish.Extension)' == 'libSkiaSharp.pdb'" />
    </ItemGroup>
  </Target>
</Project>
